# Generated by Django 4.2.20 on 2025-05-01 14:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('book', '0002_reservation'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='reservation',
            name='table_id',
        ),
    ]
