# Generated by Django 4.2.20 on 2025-05-03 11:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('book', '0005_reservation_guest_name_reservation_guest_phone'),
    ]

    operations = [
        migrations.AddField(
            model_name='reservation',
            name='updated_on',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
