# Generated by Django 4.2.20 on 2025-05-08 09:48

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('menu', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='MenuItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('description', models.TextField()),
                ('cost', models.DecimalField(decimal_places=2, max_digits=5)),
                ('category', models.CharField(choices=[('Starter', 'Starter'), ('Main', 'Main'), ('Soup', 'Soup'), ('Side', 'Side'), ('Dessert - Traditional', 'Dessert - Traditional'), ('Dessert - Other', 'Dessert - Other'), ('Drink - Hot', 'Drink - Hot'), ('Drink - Cocktail', 'Drink - Cocktail'), ('Drink - Nonalcoholic', 'Drink - Nonalcoholic'), ('Drink - Spirit', 'Drink - Spirit'), ('Drink - Beer', 'Drink - Beer'), ('Drink - Mixer', 'Drink - Mixer')], max_length=50)),
                ('menu', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='menu.menu')),
            ],
            options={
                'ordering': ['category', 'name'],
            },
        ),
    ]
